export const APP_SOURCE = {
  CLIENT: 'client',
  POS: 'pos',
  DRIVER: 'driver',
};

export const APP_SOURCE_LABELS = {
  [APP_SOURCE.CLIENT]: 'Client',
  [APP_SOURCE.POS]: 'Pos',
  [APP_SOURCE.DRIVER]: 'Driver',
};

export const APP_SOURCES_OPTIONS = [
  { label: APP_SOURCE_LABELS[APP_SOURCE.CLIENT], value: APP_SOURCE.CLIENT },
  { label: APP_SOURCE_LABELS[APP_SOURCE.POS], value: APP_SOURCE.POS },
  { label: APP_SOURCE_LABELS[APP_SOURCE.DRIVER], value: APP_SOURCE.DRIVER },
];

export const PLATFORM_DEFAULT_APP_SOURCE = {
  WEB: 'web',
  APP: 'app',
  WINDOW_APP: 'windowApp',
};

export const PLATFORM_DEFAULT_APP_SOURCE_LABELS = {
  [PLATFORM_DEFAULT_APP_SOURCE.WEB]: 'Web',
  [PLATFORM_DEFAULT_APP_SOURCE.APP]: 'App',
  [PLATFORM_DEFAULT_APP_SOURCE.WINDOW_APP]: 'Window App',
};

export const PLATFORM_DEFAULT_APP_SOURCES_OPTIONS = [
  {
    label: PLATFORM_DEFAULT_APP_SOURCE_LABELS[PLATFORM_DEFAULT_APP_SOURCE.WEB],
    value: PLATFORM_DEFAULT_APP_SOURCE.WEB,
  },
  {
    label: PLATFORM_DEFAULT_APP_SOURCE_LABELS[PLATFORM_DEFAULT_APP_SOURCE.APP],
    value: PLATFORM_DEFAULT_APP_SOURCE.APP,
  },
  {
    label: PLATFORM_DEFAULT_APP_SOURCE_LABELS[PLATFORM_DEFAULT_APP_SOURCE.WINDOW_APP],
    value: PLATFORM_DEFAULT_APP_SOURCE.WINDOW_APP,
  },
];
