/**
 * Role-based Permission Matrix
 * Định nghĩa các modules/functions mà mỗi role được phép truy cập
 *
 * Cấu trúc:
 * {
 *   [role]: {
 *     modules: [list of accessible modules],
 *     functions: {
 *       [moduleKey]: [list of allowed functions (list, create, update, delete)]
 *     }
 *   }
 * }
 */

import { ROLE_CONSTANTS } from './roles.constants';
import { MODULE_KEYS } from './module-function-keys';

/**
 * Định nghĩa các action types được phép
 */
const ALL_ACTIONS = ['list', 'create', 'update', 'delete', 'view'] as const;
const READ_ONLY_ACTIONS = ['list', 'view'] as const;

export const ROLE_PERMISSIONS = {
  [ROLE_CONSTANTS.ADMIN]: {
    modules: [
      MODULE_KEYS.USERS_MANAGEMENT,
      MODULE_KEYS.FILES_CENTER_MANAGEMENT,
      MODULE_KEYS.BUS_MANAGEMENT,
      MODULE_KEYS.TENANT_MANAGEMENT,
      MODULE_KEYS.SUBSCRIPTION_MANAGEMENT,
      MODULE_KEYS.SETTING_MANAGEMENT,

      // Sub-modules
      MODULE_KEYS.USER_TENANT,
      MODULE_KEYS.BUS_DESIGN,
      MODULE_KEYS.BUS_SETTING,
      MODULE_KEYS.BUS_TEMPLATES,
      MODULE_KEYS.BUS_SCHEDULE_TEMPLATES,
      MODULE_KEYS.BUS_ROUTES,
      MODULE_KEYS.BUS_LAYOUT_TEMPLATES,
      MODULE_KEYS.BUS_STATIONS,
      MODULE_KEYS.BUS_PROVINCES,
      MODULE_KEYS.BUS_TYPES,
      MODULE_KEYS.BUS_SERVICES,
      MODULE_KEYS.SEAT_TYPES,

      MODULE_KEYS.DEFAULT_SETTINGS,
    ],
    functions: {
      // Admin có đầy đủ quyền CRUD trên tất cả modules
      [MODULE_KEYS.USERS_MANAGEMENT]: ALL_ACTIONS,
      [MODULE_KEYS.USER_TENANT]: ALL_ACTIONS,
      [MODULE_KEYS.FILES_CENTER_MANAGEMENT]: ALL_ACTIONS,
      
      [MODULE_KEYS.BUS_MANAGEMENT]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_DESIGN]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_SETTING]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_TEMPLATES]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_SCHEDULE_TEMPLATES]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_ROUTES]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_LAYOUT_TEMPLATES]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_STATIONS]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_PROVINCES]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_TYPES]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_SERVICES]: ALL_ACTIONS,
      [MODULE_KEYS.SEAT_TYPES]: ALL_ACTIONS,

      [MODULE_KEYS.TENANT_MANAGEMENT]: ALL_ACTIONS,
      [MODULE_KEYS.SUBSCRIPTION_MANAGEMENT]: ALL_ACTIONS,


      // Settings modules
      [MODULE_KEYS.DEFAULT_SETTINGS]: ALL_ACTIONS,
    },
  },

  [ROLE_CONSTANTS.TENANT]: {
    modules: [
      MODULE_KEYS.FILES_CENTER_MANAGEMENT,
      MODULE_KEYS.GOODS_MANAGEMENT,
      MODULE_KEYS.BUS_MANAGEMENT,
      MODULE_KEYS.USERS_MANAGEMENT,
      MODULE_KEYS.PROMOTION_MANAGEMENT,
      MODULE_KEYS.BOOKING_MANAGEMENT,
      MODULE_KEYS.PAYMENT_MANAGEMENT,

      MODULE_KEYS.SETTING_MANAGEMENT,
      // Sub-modules
      MODULE_KEYS.USER_CLIENT,
      MODULE_KEYS.USER_DRIVER,
      MODULE_KEYS.USER_POS,
      MODULE_KEYS.USER_TENANT_OPERATOR,
      MODULE_KEYS.BUS_SCHEDULE,
      MODULE_KEYS.BUS_SCHEDULE_CALENDAR,
      MODULE_KEYS.BUS_DESIGN,
      MODULE_KEYS.BUS_SETTING,
      MODULE_KEYS.BUS_TEMPLATES,
      MODULE_KEYS.BUS_SCHEDULE_TEMPLATES,
      MODULE_KEYS.BUS_ROUTES,
      MODULE_KEYS.BUS_LAYOUT_TEMPLATES,
      MODULE_KEYS.BUS_STATIONS,
      MODULE_KEYS.BUS_PROVINCES,
      MODULE_KEYS.BUS_TYPES,
      MODULE_KEYS.BUS_SERVICES,
      MODULE_KEYS.SEAT_TYPES,
      MODULE_KEYS.BUS_SCHEDULE_AUTOGENERATORS,
      MODULE_KEYS.GOODS,
      MODULE_KEYS.GOODS_CATEGORIES,

      // Settings sub-modules
      MODULE_KEYS.THEME_SETTINGS,
      MODULE_KEYS.BUS_SCHEDULE_SETTINGS,
      MODULE_KEYS.ORGANIZATION_SETTINGS,
    ],
    functions: {
      [MODULE_KEYS.USERS_MANAGEMENT]: ALL_ACTIONS,
      [MODULE_KEYS.USER_CLIENT]: ALL_ACTIONS,
      [MODULE_KEYS.USER_DRIVER]: ALL_ACTIONS,
      [MODULE_KEYS.USER_POS]: ALL_ACTIONS,
      [MODULE_KEYS.USER_TENANT_OPERATOR]: ALL_ACTIONS,
      [MODULE_KEYS.FILES_CENTER_MANAGEMENT]: ALL_ACTIONS,
      [MODULE_KEYS.GOODS_MANAGEMENT]: ALL_ACTIONS,
      [MODULE_KEYS.GOODS]: ALL_ACTIONS,
      [MODULE_KEYS.GOODS_CATEGORIES]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_MANAGEMENT]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_SCHEDULE]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_SCHEDULE_CALENDAR]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_DESIGN]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_SETTING]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_TEMPLATES]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_SCHEDULE_TEMPLATES]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_ROUTES]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_LAYOUT_TEMPLATES]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_STATIONS]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_PROVINCES]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_TYPES]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_SERVICES]: ALL_ACTIONS,
      [MODULE_KEYS.SEAT_TYPES]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_SCHEDULE_AUTOGENERATORS]: ALL_ACTIONS,

      [MODULE_KEYS.PROMOTION_MANAGEMENT]: ALL_ACTIONS,
      [MODULE_KEYS.BOOKING_MANAGEMENT]: ALL_ACTIONS,
      [MODULE_KEYS.PAYMENT_MANAGEMENT]: ALL_ACTIONS,

      // Settings modules
      [MODULE_KEYS.THEME_SETTINGS]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_SCHEDULE_SETTINGS]: ALL_ACTIONS,
      [MODULE_KEYS.ORGANIZATION_SETTINGS]: ALL_ACTIONS,
    },
  },

  [ROLE_CONSTANTS.TENANT_OPERATOR]: {
    modules: [
      MODULE_KEYS.BUS_MANAGEMENT,
      MODULE_KEYS.BUS_SCHEDULE,
      MODULE_KEYS.BUS_SCHEDULE_CALENDAR,
      MODULE_KEYS.BUS_DESIGN,
      MODULE_KEYS.BUS_TEMPLATES,
      MODULE_KEYS.BUS_SCHEDULE_TEMPLATES,
      MODULE_KEYS.BUS_ROUTES,
      MODULE_KEYS.BUS_LAYOUT_TEMPLATES,
      MODULE_KEYS.BUS_SCHEDULE_AUTOGENERATORS,
      MODULE_KEYS.USERS_MANAGEMENT,
      // Sub-modules
      MODULE_KEYS.USER_CLIENT,
      MODULE_KEYS.USER_DRIVER,
      MODULE_KEYS.USER_POS,
    ],
    functions: {
      [MODULE_KEYS.BUS_MANAGEMENT]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_SCHEDULE]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_SCHEDULE_CALENDAR]: ALL_ACTIONS,
      [MODULE_KEYS.BUS_DESIGN]: READ_ONLY_ACTIONS,
      [MODULE_KEYS.BUS_TEMPLATES]: READ_ONLY_ACTIONS,
      [MODULE_KEYS.BUS_SCHEDULE_TEMPLATES]: READ_ONLY_ACTIONS,
      [MODULE_KEYS.BUS_ROUTES]: READ_ONLY_ACTIONS,
      [MODULE_KEYS.BUS_LAYOUT_TEMPLATES]: READ_ONLY_ACTIONS,
      [MODULE_KEYS.BUS_SCHEDULE_AUTOGENERATORS]: ALL_ACTIONS,
    },
  },
} as const;

/**
 * Kiểu dữ liệu cho role permissions
 */
export type RolePermissionKey = keyof typeof ROLE_PERMISSIONS;
export type RoleModules = typeof ROLE_PERMISSIONS[RolePermissionKey]['modules'];
export type RoleFunctions = typeof ROLE_PERMISSIONS[RolePermissionKey]['functions'];

/**
 * Helper types cho type-safe permission checking
 */
export interface IUserPermission {
  roles: string[];
}
